### ISSUE TITLE
请问有提供下载的dmg吗？

### ISSUE THREAD

**Issue by chlins** [zhihaozhang/TuringCalendar#1]

**Comment by zhihaozhang** [comment]
https://github.com/zhihaozhang/TuringCalendar/releases/tag/1.0 , 点击TuringCalendar.zip下载即可。

**Comment by chlins** [comment]
感谢 不过对系统版本要求有点高啊

**Comment by chlins** [comment]
<img width="448" alt="2018-02-12 1 58 38" src="https://user-images.githubusercontent.com/31262637/36084951-d95aa292-0ffc-11e8-9c8d-56577730e9cf.png">

**Comment by zhihaozhang** [comment]
不好意思，已经把系统要求降低到了10.10

**Comment by chlins** [comment]
软件是否还需安装其他依赖呢？打开运行报错
<img width="440" alt="2018-02-12 2 46 16" src="https://user-images.githubusercontent.com/31262637/36085826-9314a358-1003-11e8-898b-b4e673f205a0.png">

**Comment by GarenLiang** [comment]
无法打开,点击问号后显示弹窗
![image](https://user-images.githubusercontent.com/15516507/36518377-19cd1410-17c1-11e8-8ae2-d15a733dcc2a.png)
![image](https://user-images.githubusercontent.com/15516507/36518407-377b3582-17c1-11e8-8ed1-16e7932d66a8.png)

**Comment by zhihaozhang** [comment]
https://github.com/zhihaozhang/TuringCalendar/releases/tag/1.0 dmg文件可供下载。
